# See http://pre-commit.com/#python
# See https://github.com/pre-commit/pre-commit-hooks
# Run 'pre-commit install' to install the pre-commit hooks
# Reference: https://medium.com/@marcdomenechvila/automatic-qa-code-pre-commit-b6dbe9332e01

default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=5000"]
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: mixed-line-ending
      - id: requirements-txt-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.4
    hooks:
      # Run the linter.
      - id: ruff
        name: ruff
        description: "Run 'ruff' for extremely fast Python linting"
        entry: ruff check --force-exclude
        language: system
        require_serial: true
        types_or: [ python, pyi ]
        args: [ --fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi ]
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
        name: Relative to absolute import in F2 modules
        types: [file, python]
        args: ["--application-directories=agents"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
    hooks:
      - id: autoflake
        args: ["--in-place", "--remove-all-unused-imports"]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-tabs
        exclude: '[mM]akefile'
  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile=black"]
        additional_dependencies: ["toml"]
  - repo: https://github.com/Qarik-Group/gitlab-codeowners-linter
    rev: v1.0.2
    hooks:
      - id: gitlab-codeowners-linter
        args: ["--codeowners_file=.github/CODEOWNERS"]
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'trufflehog3 git --since HEAD'
        language: system
        stages: ["pre-commit"]
  - repo: https://github.com/PyCQA/bandit
    rev: "1.8.0"
    hooks:
      - id: bandit
        args: ["--configfile=bandit.yaml"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.14.0'
    hooks:
    - id: mypy
      additional_dependencies: [tokenize-rt==3.2.0]
      exclude:
        '^(templates/|docs/)'
      types_or: [python, pyi]
      args:
        [
          --strict,
          --ignore-missing-imports,
          --install-types,
          --non-interactive,
          --explicit-package-bases,
        ]
      require_serial: true
  # @todo: add vulture (https://github.com/jendrikseipp/vulture/blob/main/.pre-commit-hooks.yaml)
